# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nextbus}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Greg Sterndale"]
  s.date = %q{2010-02-23}
  s.description = %q{NextBus API client}
  s.email = %q{gsterndale@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "doc/ERM.graffle",
     "doc/MBTA_XML_Feed_Trial_Docs_13Nov09-1.pdf",
     "lib/attr_with_default.rb",
     "lib/instantiate_with_attrs.rb",
     "lib/nextbus.rb",
     "lib/nextbus/agency.rb",
     "lib/nextbus/client.rb",
     "lib/nextbus/direction.rb",
     "lib/nextbus/mash_extensions.rb",
     "lib/nextbus/prediction.rb",
     "lib/nextbus/report.rb",
     "lib/nextbus/route.rb",
     "lib/nextbus/stop.rb",
     "lib/nextbus/string_extensions.rb",
     "lib/nextbus/vehicle.rb",
     "nextbus.gemspec",
     "test/fixtures/agency_list.xml",
     "test/fixtures/error.xml",
     "test/fixtures/predictions.xml",
     "test/fixtures/predictions_for_multi_stops.xml",
     "test/fixtures/route_config.xml",
     "test/fixtures/route_list.xml",
     "test/fixtures/vehicle_locations.xml",
     "test/helper.rb",
     "test/unit/test_agency.rb",
     "test/unit/test_attr_with_default.rb",
     "test/unit/test_client.rb",
     "test/unit/test_direction.rb",
     "test/unit/test_instantiate_with_attrs.rb",
     "test/unit/test_mash_extensions.rb",
     "test/unit/test_nextbus.rb",
     "test/unit/test_prediction.rb",
     "test/unit/test_report.rb",
     "test/unit/test_route.rb",
     "test/unit/test_stop.rb",
     "test/unit/test_string_extensions.rb",
     "test/unit/test_vehicle.rb",
     "vendor/cache/columnize-0.3.1.gem",
     "vendor/cache/crack-0.1.6.gem",
     "vendor/cache/hashie-0.1.8.gem",
     "vendor/cache/httparty-0.5.2.gem",
     "vendor/cache/linecache-0.43.gem",
     "vendor/cache/mocha-0.9.8.gem",
     "vendor/cache/rake-0.8.7.gem",
     "vendor/cache/ruby-debug-0.10.3.gem",
     "vendor/cache/ruby-debug-base-0.10.3.gem"
  ]
  s.homepage = %q{http://github.com/neweryankee/nextbus}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{NextBus API client}
  s.test_files = [
    "test/helper.rb",
     "test/unit/test_agency.rb",
     "test/unit/test_attr_with_default.rb",
     "test/unit/test_client.rb",
     "test/unit/test_direction.rb",
     "test/unit/test_instantiate_with_attrs.rb",
     "test/unit/test_mash_extensions.rb",
     "test/unit/test_nextbus.rb",
     "test/unit/test_prediction.rb",
     "test/unit/test_report.rb",
     "test/unit/test_route.rb",
     "test/unit/test_stop.rb",
     "test/unit/test_string_extensions.rb",
     "test/unit/test_vehicle.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

